apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: default
  labels:
    app: jenkins-agent

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-agent
  namespace: default
  labels:
    app: jenkins-agent
subjects:
- kind: ServiceAccount
  name: jenkins-agent
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
